name: 'Java Scripting w/jbang'
description: 'Run java as scripts with https:/jbang.dev from your github repo'
branding:
  icon: hash
  color: red
inputs:
  jbangargs:
      description: 'Arguments for jbang'
      required: false
  script:
      description: 'Script file to run'
      required: true
  args:
      description: 'arguments to pass on to the script'
      required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.jbangargs }}
    - ${{ inputs.script }}
    - ${{ inputs.args }}
